var questions = 
  ["You are almost never late for your appointments.",
  "You like to be engaged in an active and fast-paced job.",
  "You enjoy having a wide circle of acquaintances.",
  "You feel involved when watching TV soaps.",
  "You are usually the first to react to a sudden event: the telephone ringing or unexpected question.",
  "You feel that the world is founded on compassion.",
  "You think that everything in the world is relative.",
  "Strict observance of the established rules is likely to prevent attaining a good outcome.",
  "It is difficult to get you excited.",
  "When making a decision, you rely more on your feelings than on analysis of the situation.",
  "You often think about humankind and its destiny.",
  "You believe the best decision is one which can be easily changed.",
  "You often ponder the root cause of phenomena and things.",
  "You prefer to act immediately rather than speculate about various options.",
  "You trust reason rather than feelings.",
  "You are inclined to rely more on improvisation than on prior planning.",
  "You spend your leisure time actively socializing with a group of people, attending parties, shopping, etc.",
  "You usually plan your actions in advance.",
  "Your actions are frequently influenced by your emotions.",
  "You are a person somewhat reserved and distant in communication.",
  "You know how to put every minute of your time to good purpose.",
  "You often contemplate the complexity of life.",
  "After prolonged socializing you feel you need to get away and be alone.",
  "You often do jobs in a hurry.",
  "You easily see the general principle behind specific occurrences.",
  "You frequently and easily express your feelings and emotions.",
  "You find it difficult to speak loudly.",
  "You get bored if you have to read theoretical books.",
  "You tend to sympathize with other people.",
  "You value justice higher than mercy.",
  "You rapidly get involved in the social life of a new workplace.",
  "The more people you speak to, the better you feel.",
  "You tend to rely on your experience rather than on theoretical alternatives.",
  "As a rule, you proceed only when you have a clear and detailed plan.",
  "You easily empathize with the concerns of other people.",
  "Often you prefer to read a book than go to a party.",
  "When with a group of people, you enjoy being directly involved and being at the centre of attention.",
  "You are more inclined to experiment than to follow familiar approaches.",
  "You are strongly touched by the stories about people's troubles.",
  "Deadlines seem to you to be of relative rather than absolute importance.",
  "You prefer to isolate yourself from outside noises.",
  "For you, it is easier to gain knowledge through hands-on experience than from books or manuals.",
  "You think that almost everything can be analyzed.",
  "For you, no surprises is better than surprises - bad or good ones.",
  "You take pleasure in putting things in order.",
  "You feel at ease in a crowd.",
  "You have good control over your desires and temptations.",
  "You easily understand new theoretical principles.",
  "You usually place yourself nearer to the side than in the center of the room.",
  "When solving a problem you would rather follow a familiar approach than seek a new one.",
  "A thirst for adventure is something close to your heart.",
  "When considering a situation you pay more attention to the current situation and less to a possible sequence of events.",
  "When solving a problem you consider the rational approach to be the best.",
  "You find it difficult to talk about your feelings.",
  "Your decisions are based more on the feeling of a moment than on the thorough planning.",
  "You prefer to spend your leisure time alone or relaxing in a tranquil atmosphere.",
  "You feel more comfortable sticking to conventional ways.",
  "You are easily affected by strong emotions.",
  "You are always looking for opportunities.",
  "As a rule, current preoccupations worry you more than your future plans.",
  "It is easy for you to communicate in social situations.",
  "You rarely deviate from your habits.",
  "You willingly involve yourself in matters which engage your sympathies.",
  "You easily perceive various ways in which events could develop.",
  "I enjoy wild flights of fantasy.",
  "I try to forgive and forget.",
  "I cheer people up.",
  "I feel crushed by setbacks.",
  "I reveal little about myself.",
  "I believe that people seldom tell you the whole truth.",
  "I am easily hurt.",
  "I oppose authority.",
  "I enjoy my privacy.",
  "I dislike myself.",
  "I can take strong measures.",
  "I start conversations.",
  "I resist authority.",
  "I talk to a lot of different people at parties.",
  "I get confused easily.",
  "I do things by the book.",
  "I leave a mess in my room.",
  "I get chores done right away.",
  "I am quick to judge others.",
  "I seldom feel blue.",
  "I read a lot.",
  "I don't mind being the center of attention.",
  "I counter others' arguments.",
  "I spend time thinking about past mistakes.",
  "I am not easily bothered by things.",
  "I often use tried and true methods to solve problems.",
  "Others would describe me as a social butterfly.",
  "It does not take people very long to get to know me.",
  "I often put off making decisions in case something about the situation changes.",
  "At the beginning of a meeting, I like to get started working right away.",
  "Others would describe me as logical and analytical.",
  "I am adaptable.",
  "I find it difficult to meet new people.",
  "I have a strong ability to recall details.",
  "I like routine.",
  "People tell me I’m a good listener.",
  "I enjoy brainstorming various possibilities.",
  "I see rules and laws as black and white.",
  "Others would describe me as reserved and quiet.",
  "I do my best work under the pressure of an upcoming deadline.",
  "I am organized.",
  "Compassion is more important to me than fairness.",
  "I work in spurts of energy.",
  "I have many friends.",
  "Even if I don’t agree with other's choices, I can still see things from their perspective.",
  "Deadlines are not set in stone.",
  "I plan ahead so I have no problem meeting deadlines.",
  "I would rather make the right decision, even if it means hurting someone else’s feelings.",
  "When someone has a problem, I start by offering emotional support, rather than advice.",
  "I am very observant.",
  "I prefer to communicate with others one-on-one or in small groups.",
  "I often sugar-coat my feedback.",
  "I prefer to communicate with others in a large group.",
  "I am very driven and self-disciplined.",
  "I have great ideas, but they are often not realistic.",
  "I often get wrapped up in my own thoughts and forget what’s going on around me.",
  "I do not let my emotions get in the way of my decisions.",
  "I take frequent breaks while working.",
  "I am more convinced by a logical explanation, rather than an emotional appeal.",
  "I prefer to “go with my gut”.",
  "Others would describe me as compassionate and empathic.",
  "Plans are just a starting point, and can be changed at any time.",
  "I focus on the big picture.",
  "I can’t stand leaving things unfinished.",
  "I sometimes jump right into a project without really thinking things through.",
  "After a stressful day, I need some time alone to relax.",
  "I always get my work done before relaxing.",
  "Talking with others energizes me.",
  "I can start conversations easily, even if it’s with someone I just met.",
  "I am able to make decisions quickly.",
  "My workspace is often messy.",
  "When someone has a problem, I start by offering advice, rather than emotional support.",
  "I focus on details when making a decision.",
  "I have no problem changing plans.",
  "I can’t stand when others change plans at the last-minute.",
  "I prefer to work alone.",
  "I have trouble starting conversations with someone I just met, but not with people I know well.",
  "To others, I seem like an open book.",
  "Productivity is best measured by tangible results.",
  "I focus on the 'big picture' when making a decision.",
  "I am very detail-oriented.",
  "I prefer to work with others.",
  "I avoid confrontation because I don’t like hurting others’ feelings.",
  "My actions are often influenced by my emotions.",
  "I am unconventional.",
  "I am very imaginative.",
  "I seek out feedback from others, even if I know it may be negative.",
  "I would rather be called practical than inventive.",
  "I often see possibilities, even when others can’t.",
  "I worry that others may view me as reserved and cold.",
  "The best way to accomplish things is by making an organized list.",
  "At the beginning of a meeting, I like to have a friendly conversation.",
  "I often feel overwhelmed when many people are around.",
  "I prefer “tried and true” approaches to solving problems.",
  "I often react emotionally to feedback.",
  "I would prefer to take a practical class, rather than a theoretical class.",
  "I sometimes think about things too long, rather than just jumping right into a project.",
  "You find it difficult to introduce yourself to other people.",
  "You often get so lost in thoughts that you ignore or forget your surroundings.",
  "You try to respond to your e-mails as soon as possible and cannot stand a messy inbox.",
  "You find it easy to stay relaxed and focused even when there is some pressure.",
  "You do not usually initiate conversations.",
  "You rarely do something just out of sheer curiosity.",
  "You feel superior to other people.",
  "Being organized is more important to you than being adaptable.",
  "You are usually highly motivated and energetic.",
  "Winning a debate matters less to you than making sure no one gets upset.",
  "You often feel as if you have to justify yourself to other people.",
  "Your home and work environments are quite tidy.",
  "You do not mind being at the center of attention.",
  "You consider yourself more practical than creative.",
  "People can rarely upset you.",
  "Your travel plans are usually well thought out.",
  "It is often difficult for you to relate to other people’s feelings.",
  "Your mood can change very quickly.",
  "In a discussion, truth should be more important than people’s sensitivities.",
  "You rarely worry about how your actions affect other people.",
  "Your work style is closer to random energy spikes than to a methodical and organized approach.",
  "You are often envious of others.",
  "An interesting book or a video game is often better than a social event.",
  "Being able to develop a plan and stick to it is the most important part of every project.",
  "You rarely get carried away by fantasies and ideas.",
  "You often find yourself lost in thought when you are walking in nature.",
  "If someone does not respond to your e-mail quickly, you start worrying if you said something wrong.",
  "As a parent, you would rather see your child grow up kind than smart.",
  "You do not let other people influence your actions.",
  "Your dreams tend to focus on the real world and its events.",
  "It does not take you much time to start getting involved in social activities at your new workplace.",
  "You are more of a natural improviser than a careful planner.",
  "Your emotions control you more than you control them.",
  "You enjoy going to social events that involve dress-up or role-play activities.",
  "You often spend time exploring unrealistic and impractical yet intriguing ideas.",
  "You would rather improvise than spend time coming up with a detailed plan.",
  "You are a relatively reserved and quiet person.",
  "If you had a business, you would find it very difficult to fire loyal but underperforming employees.",
  "You often contemplate the reasons for human existence.",
  "Logic is usually more important than heart when it comes to making important decisions.",
  "Keeping your options open is more important than having a to-do list.",
  "If your friend is sad about something, you are more likely to offer emotional support than suggest ways to deal with the problem.",
  "You rarely feel insecure.",
  "You have no difficulties coming up with a personal timetable and sticking to it.",
  "Being right is more important than being cooperative when it comes to teamwork.",
  "You think that everyone’s views should be respected regardless of whether they are supported by facts or not.",
  "You feel more energetic after spending time with a group of people.",
  "You frequently misplace your things.",
  "You see yourself as very emotionally stable.",
  "Your mind is always buzzing with unexplored ideas and plans.",
  "You would not call yourself a dreamer.",
  "You usually find it difficult to relax when talking in front of many people.",
  "Generally speaking, you rely more on your experience than your imagination.",
  "You worry too much about what other people think.",
  "If the room is full, you stay closer to the walls, avoiding the center.",
  "You have a tendency to procrastinate until there is not enough time to do everything.",
  "You feel very anxious in stressful situations.",
  "You believe that it is more rewarding to be liked by others than to be powerful.",
  "You have always been interested in unconventional and ambiguous things, e.g. in books, art, or movies.",
  "You often take initiative in social situations.",
  "I am a 'worrier'.",
  "I make friends easily.",
  "I have a vivid imagination.",
  "I trust others.",
  "I complete tasks successfully.",
  "I get angry easily.",
  "I really enjoy large parties and gatherings.",
  "I think art is important.",
  "I use and manipulate others to get my own way.",
  "I don't like things to be a mess - I like to tidy up.",
  "I often feel sad.",
  "I like to take charge of situations and events.",
  "I experience deep and varied emotions.",
  "I love to help others.",
  "I keep my promises.",
  "I find it difficult to approach others.",
  "I am always busy - always on the go.",
  "I prefer variety to routine.",
  "I love a good argument - a good fight.",
  "I work hard.",
  "I over-indulge and go on 'binges'.",
  "I love excitement.",
  "I enjoy reading challenging books and articles.",
  "I believe that I am better than others.",
  "I am always prepared.",
  "I panic easily.",
  "I am a really cheerful person.",
  "I tend to support political candidates who favour progress and reform.",
  "I sympathise with the homeless.",
  "I am very spontaneous - I act without thinking.",
  "I 'fear for the worst'.",
  "I feel comfortable around people.",
  "I enjoy 'wild flights of fantasy'.",
  "I believe that people basically have good intentions.",
  "When I do something, I always do it well.",
  "I get irritated easily.",
  "I always chat to lots of different people at parties.",
  "I see beauty in things that others might not notice.",
  "I don't mind cheating to get ahead.",
  "I often forget to put things back in their proper place.",
  "I try to be in charge - to lead others.",
  "I am empathetic - I feel others' emotions.",
  "I am concerned about others.",
  "I tell the truth.",
  "I am afraid to draw attention to myself.",
  "I never sit still - I'm always on the go.",
  "I prefer to stick with things that I know.",
  "I shout and yell at people.",
  "I do more than what's expected of me.",
  "I rarely over-indulge.",
  "I go out of my way to seek adventure.",
  "I avoid philosophical discussions.",
  "I think highly of myself.",
  "I get the job done and carry out my plans.",
  "I become overwhelmed by events.",
  "I have a lot of fun.",
  "I believe that there is no absolute right or wrong.",
  "I feel sympathy for those who are worse off than myself.",
  "I make rash decisions.",
  "I am afraid of many things.",
  "I avoid coming into contact with people if I can help it.",
  "I love to daydream.",
  "I trust what people say.",
  "I handle tasks methodically.",
  "I frequently lose my temper.",
  "I prefer to be alone.",
  "I do not like poetry.",
  "I take advantage of others.",
  "I always leave the place in a mess.",
  "I am often down in the dumps.",
  "I take control of situations.",
  "I rarely notice my emotional reactions and feelings.",
  "I am indifferent to the feelings of others.",
  "I break rules.",
  "I only really feel comfortable with friends.",
  "I do a lot in my spare time.",
  "I dislike changes.",
  "I insult people.",
  "I do just enough work to get by.",
  "I easily resist temptations.",
  "I enjoy being reckless.",
  "I have difficulty understanding abstract ideas.",
  "I waste my time.",
  "I feel that I'm unable to deal with things.",
  "I love life.",
  "I tend to support political candidates who favour conventional and traditional views.",
  "I am not interested in other people's problems.",
  "I rush into things.",
  "I get stressed out easily.",
  "I keep others at a distance.",
  "I like to get lost in thought.",
  "I distrust people.",
  "I know how to get things done.",
  "I am not easily annoyed.",
  "I avoid crowds.",
  "I do not enjoy going to art galleries or exhibitions.",
  "I am un-cooperative - I obstruct other peoples' plans.",
  "I leave my 'bits and pieces' and belongings around.",
  "I feel comfortable with myself.",
  "I wait for others to take the lead.",
  "I don't understand people who get emotional.",
  "I don't have time for other people.",
  "I break my promises.",
  "I am not bothered by difficult social situations.",
  "I like to take it easy.",
  "I am attached to conventional ways.",
  "I always even the score with others.",
  "I put little time and effort into my work.",
  "I am able to control my cravings.",
  "I act zany and outrageously.",
  "I am not interested in theoretical discussions.",
  "I boast about my virtues.",
  "I have difficulty starting tasks.",
  "I remain calm under pressure.",
  "I look at the bright side of life.",
  "I believe that we should be very tough on crime.",
  "I try not to think about the needy.",
  "I like to stay at home.",
  "I like to make definite plans when going out.",
  "I avoid public speaking whenever possible.",
  "I work best in a group or with others.",
  "I like to fix things more than I like to try and fix people.",
  "I like tests that have essay questions.",
  "I prefer to use logic and reason in my thinking first and foremost.",
  "I like to improvise whenever possible.",
  "Morality should be based on justice.",
  "I like to rely on my memory.",
  "I largely accept things as they are.",
  "I like to procrastinate.",
  "I'm largely uncomfortable with my emotions.",
  "I'm bored being alone.",
  "I like to be focused on the future.",
  "I like to talk more than I listen.",
  "I like to follow my head more than my heart.",
  "I like devoting my all to work.",
  "I prefer hard data over theory.",
  "I like to think I'm thick-skinned.",
  "My life is pretty chaotic.",
  "I prefer looking at the overall big picture.",
  "I want people's love.",
  "I find it difficult to yell at others.",
  "I prefer to stand out.",
  "I like to plan things at the last minute.",
  "I feel I'm more energetic than laid-back.",
  "I like to tell people what an event meant to me personally, rather than just describing it.",
  "I like to keep my room clean.",
  "Parties wear me out pretty quickly.",
  "I tend to believe what others tell me wholeheartedly.",
  "I like to know the 'why' of things.",
  "I like to keep my options open.",
  "I like to go out rather than stay home.",
  "I like to perform in front of others.",
  "I work best when I'm alone.",
  "I like to try and fix people more than I like to fix things.",
  "I prefer to take a multiple choice test.",
  "I think logic is sometimes overrated.",
  "I like to prepare for things rather than just doing things on the fly.",
  "Morality should be based on compassion.",
  "I like to make lists to help my memory.",
  "I'm generally unsatisfied with the way things are.",
  "I like to get my work done as soon as I can.",
  "I need time to be by myself.",
  "I'm focused on living in the here and now.",
  "I like to listen more than I talk.",
  "I prefer to follow my heart over my head.",
  "I like to play hard more than work hard.",
  "I prefer theory over hard data.",
  "I am easily hurt by others' words.",
  "My life is pretty organized.",
  "I always like to get as much detail as possible.",
  "I want people's respect more than their love.",
  "I don't mind yelling when I need to.",
  "I prefer to fit in than stand out.",
  "I like to plan far ahead.",
  "I feel like I'm more laid-back than energetic.",
  "When I talk about an event, I prefer to keep to the facts rather than describe what it meant to me.",
  "I just put stuff wherever, it doesn't need to go in a specific place.",
  "I love and get fired up by parties or social gatherings.",
  "I'm pretty skeptical about most things.",
  "I like to know the 'who', 'what' and 'when' of things.",
  "I like fishing.",
  "I love playing games.",
  "I love spending time on social media.",
  "I like to cook.",
  "I love reading newspapers.",
  "I love spending time on my computer.",
  "I love music.",
  "I enjoy being intoxicated.",
  "I love playing friend.fail.",
  "I dream of being famous.",
  "I dream of being rich.",
  "I dream of starting my own business.",
  "I dream of being the center of sexual attention.",
  "I consider myself better looking than average.",
  "I consider myself having better taste in clothing than average.",
  "I consider myself a better driver than average.",
  "I consider myself romantic.",
  "I consider my life to be the best of the people around this table.",
  "I feel desperate.",
  "I easily resist temptations.",
  "I get others to do my duties.",
  "I am not easily embarrassed.",
  "I am always on the go.",
  "I cheat to get ahead.",
  "I experience my emotions intensely.",
  "I make people feel uncomfortable.",
  "I seek quiet.",
  "I hate to seem pushy.",
  "I rarely notice my emotional reactions.",
  "I am always busy.",
  "I dislike new foods.",
  "I get overwhelmed by emotions.",
  "I warm up quickly to others.",
  "I keep others at a distance.",
  "I find it difficult to approach others.",
  "I involve others in what I am doing.",
  "I rarely overindulge.",
  "I do crazy things.",
  "I react quickly.",
  "I set high standards for myself and others.",
  "I am not really interested in others.",
  "I panic easily.",
  "I have little to contribute.",
  "I am calm even in tense situations.",
  "I am not highly motivated to succeed.",
  "I try to lead others.",
  "I am willing to try anything once.",
  "I make people feel welcome.",
  "I plunge into tasks with all my heart.",
  "I express childlike joy.",
  "I often make last-minute plans.",
  "I don't see the consequences of things.",
  "I laugh my way through life.",
  "I suffer from others' sorrows.",
  "I love to daydream.",
  "I consider myself an average person.",
  "I avoid difficult reading material.",
  "I am not easily disturbed by events.",
  "I see beauty in things that others might not notice.",
  "I am afraid that I will do the wrong thing.",
  "I can handle a lot of information.",
  "I often eat too much.",
  "I love flowers.",
  "I tell the truth.",
  "I work hard.",
  "I laugh aloud.",
  "I turn my back on others.",
  "I break my promises.",
  "I go straight for the goal.",
  "I make myself the center of attention.",
  "I come up with good solutions.",
  "I lose my temper.",
  "I like to act on a whim.",
  "I look down on others.",
  "I am indifferent to the feelings of others.",
  "I believe that there is no absolute right or wrong.",
  "I love to eat.",
  "I am passionate about causes.",
  "I believe that too much tax money goes to support artists.",
  "I hold a grudge.",
  "I believe that we coddle criminals too much.",
  "I believe that others have good intentions.",
  "I listen to my conscience.",
  "I don't like the idea of change.",
  "I waste my time.",
  "I adapt easily to new situations.",
  "I avoid mistakes.",
  "I indulge in my fantasies.",
  "I boast about my virtues.",
  "I can manage many things at the same time.",
  "I like a leisurely lifestyle.",
  "I amuse my friends.",
  "I feel comfortable with myself.",
  "I try to follow the rules.",
  "I try to understand myself.",
  "I suspect hidden motives in others.",
  "I have difficulty starting tasks.",
  "I don't know why I do some of the things I do.",
  "I do not have a good imagination.",
  "I choose my words with care.",
  "I like to tidy up.",
  "I know the answers to many questions.",
  "I am interested in many things.",
  "I don't worry about things that have already happened.",
  "I enjoy the beauty of nature.",
  "I am not interested in other people's problems.",
  "I tend to vote for liberal political candidates.",
  "I never spend more than I can afford.",
  "I contradict others.",
  "I am not bothered by messy people.",
  "I turn plans into actions.",
  "I do not like concerts.",
  "I readily overcome setbacks.",
  "I can handle complex problems.",
  "I am able to control my cravings.",
  "I dislike loud music.",
  "I excel in what I do.",
  "I am able to stand up for myself.",
  "I rarely complain.",
  "I pretend to be concerned for others.",
  "I believe that people are essentially evil.",
  "I believe in an eye for an eye.",
  "I am very pleased with myself.",
  "I do not enjoy watching dance performances.",
  "I can't stand weak people.",
  "I know how to get around the rules.",
  "I am comfortable in unfamiliar situations.",
  "I pay my bills on time.",
  "I get caught up in my problems.",
  "I love surprise parties.",
  "I often feel uncomfortable around others.",
  "I seek danger.",
  "I dislike talking about myself.",
  "I use flattery to get ahead.",
  "I would never cheat on my taxes.",
  "I am not easily amused.",
  "I am easy to satisfy.",
  "I believe that people should fend for themselves.",
  "I do things I later regret.",
  "I avoid philosophical discussions.",
  "I believe that criminals should receive help rather than punishment.",
  "I feel others' emotions.",
  "I take advantage of others.",
  "I like to stand during the national anthem.",
  "I can't stand confrontations.",
  "I am afraid of many things.",
  "I am not bothered by difficult social situations.",
  "I tend to dislike softhearted people.",
  "I would never go hang-gliding or bungee-jumping.",
  "I have a rich vocabulary.",
  "I prefer to stick with things that I know.",
  "I keep in the background.",
  "I hold back my opinions.",
  "I like to visit new places.",
  "I keep my cool.",
  "I feel that my life lacks direction.",
  "I do not enjoy going to art museums.",
  "I tend to vote for conservative political candidates.",
  "I enjoy examining myself and my life.",
  "I value cooperation over competition.",
  "I like to take my time.",
  "I need a push to get started.",
  "I love a good fight.",
  "I wait for others to lead the way.",
  "I believe that people are basically moral.",
  "I have a sharp tongue.",
  "I love excitement.",
  "I believe in one true religion.",
  "I am always prepared.",
  "I postpone decisions.",
  "I can talk others into doing things."];
